djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("social_app.urls"), name="social"),
    path("__debug__/", include("debug_toolbar.urls")),
    path('api-auth/', include('rest_framework.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_app/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views


app_name = "social"



urlpatterns = [
    # pages
    path('', views.homepage, name='home'),
    path("contactUs/", views.ticket, name="contact_us"),
    path('posts/', views.post_list, name="posts"),
    path('posts/tag/<str:tag_slug>', views.post_list, name="get_posts_tag"),
    path('profile/', views.profile, name="profile"),
    path('posts/detail/<pk>/', views.detail_post, name="detail"),
    path('posts/page/<str:page>/', views.post_list, name="posts by page"),
    path('posts/page/<str:tag_slug>/<str:page>/', views.post_list, name="posts by page and tag"),
    path('posts/edit-and-delete/', views.change_posts, name="change_posts"),

    # login or log out
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path('logout/', views.log_out, name="logout"),

    # sign up
    path('register/', views.register, name="register"),
    path('user/edit/', views.ProfileEdit, name="ProfileEdit"),

    # forms
    path('posts/create_post/', views.add_post, name="Add New Post"),
    path('search/', views.search_post, name="search post"),
    path('add-post/<pk>/', views.add_post, name="Add New Post"),
    path('add-comments/<pk>/', views.add_comment, name="add comment"),

    # Edit And Delete Posts
    path('posts/edit/<pk>/', views.edit_post, name='edit post'),
    path('posts/delete/<pk>/', views.delete_post, name='delete post'),

    # like post
    path('like-post/', views.like_post, name='like post'),

    # save and un save
    path('posts/save/', views.save_post, name='save post'),

    # get users ot user detail
    path('users/', views.get_all_users, name='get all users'),
    path('users/<username>', views.get_user_detail_by_username, name="get user detail by username"),

     # follow
    path('follow/', views.follow_user, name='follow user'),

    path('api/posts/', views.all_posts_api, name='all posts'),
    path('api/posts/<post_id>', views.posts_api, name="crud in a post"),

    path('api/cbv/posts/', views.ManageAllPostsView.as_view()),
    path('api/cbv/posts/<post_id>/', views.ManageDetailPostView.as_view())

]

social_app/models.py
import os

from django.db import models
from django.contrib.auth.models import AbstractUser
from taggit.managers import TaggableManager
from django.urls import reverse

# Create your models here.


class User(AbstractUser):
    date_of_birth = models.DateTimeField(blank=True, null=True)
    bio = models.CharField(max_length=500, blank=True, null=True)
    photo = models.ImageField(upload_to="users-photo/", blank=True, null=True)
    job = models.CharField(max_length=500, blank=True, null=True)
    phone = models.CharField(max_length=11, blank=True, null=True)
    following = models.ManyToManyField('self', through="Following", related_name='followers', symmetrical=False)

    def get_absolute_url(self):
        return reverse('social:get user detail by username', args=[self.username])

class Post(models.Model):
    """ post model for posts in my website """
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_post')
    # data fields
    discription = models.TextField(max_length=1000)

    # date
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User, related_name="post_likes", blank=True)
    saved = models.ManyToManyField(User, related_name="post_saved", blank=True)
    total_likes = models.PositiveIntegerField(default=0)

    tags = TaggableManager()

    objects = models.Manager()

    class Meta:
        """ ORDERING """
        ordering = ["-created"]
        indexes = [
            models.Index(fields=["-created"]),
            models.Index(fields=["-total_likes"]),
        ]

    def __str__(self):
        """ str for class """
        return self.discription

    def delete(self, *args, **kwargs):
        for image in self.images.all():
            storage, path = image.image.storage, image.image.path
            storage.delete(path)
        super().delete(*args, **kwargs)

    def get_absolute_url(self, *args, **kwargs):
        return reverse('social:detail', args=[self.id])



class Comments(models.Model):

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField(max_length=1000)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    post_for = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments', default='')


    def __str__(self):
        return self.text
    def get_absolute_url(self):
        return reverse('social:add_comment', args=[Post.pk])


class PostsImage(models.Model):
    image = models.ImageField(upload_to='posts-image/')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images')

    def delete(self, *args, **kwargs):
        storage, path = self.image.storage, self.image.path
        os.remove(path)
        super().delete(*args, **kwargs)


class Following(models.Model):
    user_from = models.ForeignKey(User, on_delete=models.CASCADE, related_name='rel_to_set')
    user_to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='rel_from_set')
    created_at = models.DateTimeField(auto_now_add=True)
    class Meta:
        indexes = [ models.Index(fields=['-created_at'])]
        ordering = ('-created_at',)

    def __str__(self):
        return f'{self.user_from} follows {self.user_to}'


class Ticket(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_tickets')
    body = models.TextField(max_length=1000)
    subjects = [
        ("BG", "bug"),
        ("PR", "proposal"),
        ("CR", "critics"),
    ]
    subject = models.CharField(max_length=2, choices=subjects, default='BG')
    answer = models.TextField(max_length=1000)

    def __str__(self):
        return f'{self.subject} - {self.body}'

social_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.postgres.search import TrigramSimilarity
from django.http import HttpResponse, JsonResponse
import random
from django.contrib.auth import logout, login
from .forms import *
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from .models import Post, User, Following
from taggit.models import Tag
from django.db.models import Count
from django.contrib import messages

from rest_framework import status
from rest_framework.response import Response
from rest_framework.request import Request
from rest_framework.decorators import api_view
from .serializers import *
from rest_framework.views import APIView


# Create your views here.

# region views
def log_out(request):
    logout(request)
    return HttpResponse('you have logged out')


def homepage(request):
    context = {
        "user": request.user,
        "saved_post": request.user.post_saved.all()
    }
    return render(request, 'parent/index.html', context)


def ticket(request):
    answers = Ticket.objects.filter(author=request.user)
    sent = False
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = request.user
            email_message = f'You Have a message from {user.first_name} {user.last_name} ' \
                            f'message title is {cd["subject"]}' \
                            f'message is:' \
                            f' {cd["body"]}'
            Ticket.objects.create(author=user, body=cd["body"], subject=cd["subject"])
            send_mail(cd['subject'], email_message, 'mahdimalvandi6@gmail.com',
                      ['zohrezahedi1981@gmail.com', 'mahdimll1386@gmail.com'],
                      fail_silently=False)
            sent = True

    else:
        form = TicketForm()
    context = {"form": form, 'sent': sent,
               "answers": answers
               }

    return render(request, "app/contactus.html", context)


def register(request):
    if request.method == "POST":

        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('social:home')
    else:
        form = UserRegisterForm()
    return render(request, "registration/register.html", {'form': form})


@login_required()
def ProfileEdit(request):
    if request.method == "POST":
        user_form = EditUserForm(request.POST, instance=request.user, files=request.FILES)
        if user_form.is_valid():
            user_form.save()
            return redirect("social:home")
    else:
        user_form = EditUserForm(instance=request.user)
    context = {
        'user_form': user_form,
    }
    return render(request, 'app/edit_profile.html', context)


@login_required()
def profile(request):
    user = request.user

    return HttpResponse(
        f'username => {user.username} full name => {user.first_name} {user.last_name} job => {user.job}')


def post_list(request, tag_slug=None, page=1):
    if tag_slug is not None:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = Post.objects.filter(tags__in=[tag]).order_by('-total_likes')
    else:
        posts = Post.objects.all()
        tag = None

    paginator = Paginator(posts, 1)
    page_number = page
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = []
    except PageNotAnInteger:
        posts = paginator.page(1)
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        last = posts.has_next()
        return render(request, 'partials/list-ajax.html', {'posts': posts, 'last': last})
    context = {
        'posts': posts,
        'tag': tag
    }
    return render(request, "app/blog.html", context)


@login_required
def add_post(request):
    if request.method == "POST":
        form = AddPostForm(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            post = form.save(commit=False)
            post.author = request.user

            form.save()
            form.save_m2m()
            PostsImage.objects.create(post=post, image=cd["image"])

            return redirect("social:posts")
    else:
        form = AddPostForm()
    context = {
        "form": form,
    }
    return render(request, "forms/addPostForm.html", context)


def detail_post(request, pk):
    """Get a post detail from pk

    :parameter:
        pk: int
            id of the post you want to show
    """
    post = get_object_or_404(Post, id=pk)
    posts_tag = post.tags.values_list('id', flat=True)
    similar_post = Post.objects.filter(tags__in=posts_tag).exclude(id=pk)
    similar_posts = similar_post.annotate(same_posts=Count('tags')).order_by("-same_posts")
    comments = post.comments.filter(active=True)
    context = {
        'post': post,
        'similar_posts': similar_posts,
        'comments': comments,
        'is_login': request.user.is_authenticated

    }
    return render(request, 'app/detail.html', context)


def search_post(request):
    """ Get query and search into posts by tags and discription """
    query = ""
    results = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]
            results1 = Post.objects.annotate(similarity=TrigramSimilarity('discription', query)).filter(
                similarity__gt=0.1)

            # get similar tags
            similar_tags = Post.tags.annotate(similarity=TrigramSimilarity('name', query)).filter(similarity__gt=0.1)

            # get similar posts by similar tags
            similar_post = Post.objects.filter(tags__in=similar_tags)

            # order similar posts by same tags
            results2 = similar_post.annotate(same_posts=Count('tags')).order_by("-same_posts")
            results = (results1 | results2).order_by("-similarity")
            results = results.annotate(same_posts=Count('tags')).order_by("-same_posts")

    context = {
        'posts': results,
        'query': query
    }
    return render(request, 'app/blog.html', context)


@login_required()
def add_comment(request, pk):
    """Add a comment to the Post

    :parameter :
        pk : int
            id of the post you want to add a comment to it
    """
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Comments.objects.create(author=request.user, text=cd["text"], post_for=post)
            messages.success(request, 'your message has been added')
            return redirect('social:detail', post.pk)
    else:
        form = CommentForm()

    return redirect('social:detail', pk)


@login_required
def delete_post(request, pk):
    """Delete a post from pk

    Parameters
    ----------
    pk : int
        id of the post you want to delete
    """
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('social:change_posts')


@login_required
def change_posts(request):
    """Return a HTML page"""
    return render(request, 'app/edit-buttons.html', {'posts': Post.objects.filter(author=request.user)})


@login_required
def edit_post(request, pk):
    """Edit a post from pk

    Parameters
    ----------
    pk : int
        id of the post you want to edit
    """
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = AddPostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            cd = form.cleaned_data
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            PostsImage.objects.create(image=cd['image'], post=post)

            return redirect('social:change_posts')
    else:
        form = AddPostForm(instance=post)
    context = {
        'post': post,
        'form': form
    }
    return render(request, 'forms/edit-posts.html', context)


@login_required
@require_POST
def like_post(request):
    post_id = request.POST.get('post_id')
    if post_id is not None:
        post = Post.objects.select_related('author').get(id=post_id)
        user = request.user

        if user in post.likes.all():
            # unlike
            liked = False
            post.likes.remove(user)
        else:
            # like
            liked = True
            post.likes.add(user)

        post_likes_count = post.likes.count()

        response_data = {
            'liked': liked,
            'likes_count': post_likes_count
        }
    else:
        response_data = {
            'error': 'Invalid post_id'
        }
    return JsonResponse(response_data)


@login_required
@require_POST
def save_post(request):
    post_id = request.POST.get('post_id')
    if post_id is not None:
        post = get_object_or_404(Post, id=post_id)
        user = request.user
        if user in post.saved.all():
            # unsaved
            post.saved.remove(user)
            saved = False
        else:
            # saved
            post.saved.add(user)
            saved = True
        response_data = {
            'saved': saved
        }
    else:
        response_data = {
            'error': 'Invalid post_id'
        }
    return JsonResponse(response_data)


@login_required()
def get_all_users(request):
    all_users = User.objects.filter(is_active=True)
    return render(request, 'app/users-list.html', {'users': all_users})


@login_required()
def get_user_detail_by_username(request, username):

social_app/templates/app/blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}blog{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/output.css' %}">
</head>
<body>
    <main>
        <div class="container">
            {% if tag %}
                <h1 class="text-center font-bold mt-4 text-4xl">{{ tag }}'s posts</h1>
                {% elif query %}
                <h1 class="text-center font-bold mt-4 text-4xl">{{ query }}'s posts</h1>
                {% else %}
                <h1 class="text-center font-bold mt-4 text-4xl">all posts</h1>
            {% endif %}
            <div class="flex justify-between gap-4 flex-wrap" id="posts">
{#                start box#}
                {% for post in posts %}
                    <div class="border rounded-lg bg-blue-800 overflow-hidden w-[18rem] h-[23rem]">
                    <div class="w-full h-1/2 ">
                        <img src="{{ post.images.first.image.url }}" alt="" class="w-full h-full">
                    </div>
                    <div class="w-full h-1/2 text-white p-2 flex flex-col justify-between">
                        <a href="{% url 'social:detail' post.id %}" class="line-clamp-4 ">{{ post.discription }}</a>
                        <p class="">Tags : {% for tag in post.tags.all %} <a href="{% url 'social:get_posts_tag' tag.slug %}">{{ tag }}</a>{% endfor %}</p>
                        <div class="flex justify-between">
                            <p class="" id="name">This post made by {{ post.author }} in {{ post.created|date:'y/m/d' }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}


            </div>

            <button class="load-more border ">load more</button>

        </div>
{#     {% include "partials/paginator.html" with page=posts tag=tag.slug%}#}
    </main>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
 $(document).ready(function(){
        var page = 2;
        $('.load-more').click(function(){
            $.ajax({
                type : 'GET',
                url : `{% if tag %}/posts/page/{{ tag.slug }}/${page}/{% else %}/posts/page/${page}/{% endif %}`,
                dataType : 'html',
                success : function(data){
                    $('#posts').append(data);
                    page += 1;
                }
            });
        });
    });
</script>
</body>
</html>

social_app/templates/app/contactus.html
<form method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <input type="submit" value="send">
</form>
{% if answers %}
    {% for answer in answers %}
        {% if answer.answer != '' %}
                <h2>Your Ticket Subject is '{{ answer.get_subject_display }}' and body '{{ answer.body }}' and admin answer is '{{ answer.answer }}'</h2>
        {% endif %}

    {% endfor %}
{% endif %}
{% if sent %}
    <h2>Your Ticket has been sent</h2>
{% endif %}

social_app/templates/app/detail.html
{% load static %}
{% load social_share %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}blog{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/output.css' %}">
</head>
<body>
<main>
{% if messages %}
{% for message in messages %}
 <h1>{{ message }}</h1>
{% endfor %}

{% endif %} 
    <div class="container">
        <h1 class="text-center font-bold text-4xl">post</h1>
<p>{{ post.discription }}</p>

    {% for photo in post.images.all %}
                            <img src="{{ photo.image.url }}" alt="" style="width: 20rem;">
                        {% endfor %}
<p>This post created by {{ post.author }} in {{ post.created|date:'y/m/d' }}</p>
<h2>Tags: {% for tag in post.tags.all %}
<a href="{% url 'social:get_posts_tag' tag.slug %}"> {{ tag }}</a>
{% endfor %}
</h2>
    <div class="post  " data-post-id="{{ post.id }}">
        <button class="like-btn border rounded-lg p-2">{% if request.user in post.likes.all %}
            unlike
            {% else %}
            like
        {% endif %} </button>
     <button class="save-btn border rounded-lg p-2">{% if request.user in post.saved.all %}
            unSave
            {% else %}
            Save
        {% endif %} </button>
    <p class="likes-count">{{ post.likes.count }}</p>
    </div>
    {% post_to_facebook post "Post to Facebook!" %}
{% post_to_twitter "New Song: {{ post.discription }}. Check it out!" post "Post to Twitter" %}
{% post_to_gplus post "Post to Google+!" %}
{% post_to_linkedin post %}
{% send_email post.discription "New Song: {{ post.discription }}. Check it out!" post "Share via email" %}
{% post_to_reddit "New Song: {{ post.discription }}" post %}
{% post_to_telegram "New Song: {{ post.discription }}." post %}
{% post_to_whatsapp post "Share via WhatsApp" %}
{% save_to_pinterest post %}
{% add_pinterest_script %} // Required for save_to_pinterest. Add to the end of body tag.
{% copy_to_clipboard post "Copy to clipboard!" %}
{% add_copy_script %} // Required for copy_to_clipboard. Add to the end of body tag.
<br><br><br><br><br>
<h1 class="text-center font-bold text-4xl">similar posts</h1>
{% for similar_post in similar_posts %}
    <a href="{% url 'social:detail' similar_post.id %}">{{ similar_post|truncatewords:20 }}</a>
    <br>
{% endfor %}

<div class="flex gap-4 justify-between">
        {% for post in posts %}
                    <div class="border rounded-lg bg-blue-800 overflow-hidden w-[18rem] h-[23rem]">
                    <div class="w-full h-1/2 ">


                    </div>
                    <div class="w-full h-1/2 text-white p-2 flex flex-col justify-between">
                        <a href="{% url 'social:detail' post.id %}" class="line-clamp-4 ">{{ post.discription }}</a>
                        <p class="">Tags : {% for tag in post.tags.all %} <a href="{% url 'social:get_posts_tag' tag.slug %}">{{ tag }}</a>{% endfor %}</p>
                        <div class="flex justify-between">
                            <p class="" id="name">This post made by {{ post.author }} in {{ post.created|date:'y/m/d' }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}


</div>
{% include 'forms/comments.html' %}
    </div>
</main>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    $(document).ready(function() {
        $('.like-btn').click(function() {
			var post_id = $(this).closest('.post').data('post-id');
            var  button = $(this);

            $.ajax({
                type: 'POST',
                url: '{% url 'social:like post' %}',
                data: {'post_id': post_id, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                success: function(data) {
                    if (data.liked){
                        button.text('UnLike');
                    } else {
                        button.text('Like');
                    }
                    $('.likes-count').text(data.likes_count + " likes");
                },
            });
        });
        $('.save-btn').click(function() {
			var post_id = $(this).closest('.post').data('post-id');
            var  button = $(this);

            $.ajax({
                type: 'POST',
                url: '{% url 'social:save post' %}',
                data: {'post_id': post_id, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                success: function(data) {
                    if (data.saved){
                        button.text('UnSave');
                    } else {
                        button.text('Save');
                    }
                },
            });
        });
    })

</script>
</body>
</html>

social_app/templates/app/edit-buttons.html
<h1>Which post do you want to edit?</h1>
<div class="flex gap-4 flex-wrap">
    {% for post in posts %}
        <div class="border rounded-lg p-4">
            <p class="line-clamp-4">{{ post.discription }}</p>
            <a href="{% url 'social:delete post' post.pk %}">Delete</a>
            <a href="{% url 'social:edit post' post.pk %}">Edit</a>
        </div>
    {% endfor %}
</div>

social_app/templates/app/users-list.html
{% load static %}
{% load thumbnail %}

<table class="w-full" style="width: 50%;margin: 0 auto;">
    <thead>
    <tr>
        <th>image</th>
        <th>username</th>
        <th>first name</th>
        <th>last name</th>
    </tr>
    </thead>
    {% for user in users %}
        <tr class="mt-2" style="margin-top: 1rem;">
        <td>
            {% if user.photo %}
            <img class="h-8 w-8 rounded-full" style="height: 2rem;width: 2rem;" src="{% thumbnail user.photo 40x0 quality=80 %}">
            {% else %}
            <svg class="h-8 w-8 rounded-full" style="height: 2rem;width: 2rem;" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 122.9 122.9"  xml:space="preserve"><g><path d="M61.4,0c17,0,32.3,6.9,43.4,18c11.1,11.1,18,26.5,18,43.4c0,17-6.9,32.3-18,43.4c-11.1,11.1-26.5,18-43.4,18 s-32.3-6.9-43.4-18C6.9,93.8,0,78.4,0,61.4c0-17,6.9-32.3,18-43.4C29.1,6.9,44.5,0,61.4,0L61.4,0z M41.3,54.3c-1.1,0-2,0.3-2.5,0.7 c-0.3,0.2-0.6,0.5-0.7,0.8c-0.2,0.4-0.3,0.8-0.2,1.4c0,1.5,0.8,3.5,2.4,5.8l0,0l0,0l5,8c2,3.2,4.1,6.5,6.8,8.9 c2.5,2.3,5.6,3.9,9.6,3.9c4.4,0,7.6-1.6,10.2-4.1c2.7-2.5,4.9-6,7-9.5l5.7-9.3c1.1-2.4,1.4-4,1.2-5c-0.1-0.6-0.8-0.8-1.8-0.9 c-0.2,0-0.5,0-0.7,0c-0.3,0-0.5,0-0.8,0c-0.2,0-0.3,0-0.4,0c-0.5,0-1,0-1.6-0.1l1.9-8.6c-14.4,2.3-25.2-8.4-40.4-2.1L43,54.4 C42.4,54.4,41.8,54.4,41.3,54.3L41.3,54.3L41.3,54.3L41.3,54.3z M18.8,95.7c7.1-2.5,19.6-3.8,25.4-7.7c1-1.3,2.1-2.9,3.1-4.3 c0.6-0.9,1.1-1.7,1.6-2.3c0.1-0.1,0.2-0.2,0.3-0.3c-2.4-2.5-4.4-5.5-6.3-8.5l-5-8C36,61.8,35,59.3,35,57.3c0-1,0.1-1.9,0.5-2.6 c0.4-0.8,1-1.5,1.7-2c0.4-0.2,0.8-0.5,1.2-0.6c-0.3-4.3-0.4-9.8-0.2-14.4c0.1-1.1,0.3-2.2,0.6-3.3c1.3-4.6,4.5-8.3,8.5-10.8 c1.4-0.9,2.9-1.6,4.6-2.2c2.9-1.1,1.5-5.5,4.7-5.6c7.5-0.2,19.8,6.2,24.6,11.4c2.8,3,4.6,7,4.9,12.3l-0.3,13.1l0,0 c1.4,0.4,2.3,1.3,2.7,2.7c0.4,1.6,0,3.8-1.4,6.9l0,0c0,0.1-0.1,0.1-0.1,0.2l-5.7,9.4c-2.2,3.6-4.5,7.3-7.5,10.1L73.7,82l0,0 c0.4,0.5,0.8,1.1,1.2,1.7c0.8,1.1,1.6,2.4,2.5,3.6c5.3,4.5,19.3,5.9,26.7,8.6c7.6-9.4,12.1-21.4,12.1-34.4c0-15.1-6.1-28.8-16-38.7 c-9.9-9.9-23.6-16-38.7-16s-28.8,6.1-38.7,16c-9.9,9.9-16,23.6-16,38.7C6.7,74.4,11.2,86.3,18.8,95.7L18.8,95.7z M77,90.5 c-1.4-1.6-2.8-3.7-4.1-5.5c-0.4-0.5-0.7-1.1-1.1-1.5c-2.7,2-6,3.3-10.3,3.3c-4.5,0-8-1.6-10.9-4.1c0,0,0,0.1-0.1,0.1 c-0.5,0.7-1,1.4-1.6,2.3c-1.1,1.6-2.3,3.3-3.4,4.8C45.6,100,71.1,106,77,90.5L77,90.5z"/></g></svg>
        {% endif %}
        </td>
        <td><a href="{{ user.get_absolute_url }}">{{ user.username }}</a></td>
        <td>{{ user.first_name }}</td>
        <td>{{ user.last_name }}</td>
    </tr>
    {% endfor %}


</table>